[settings]
lockfile = true

[tool_alias]
dprint = "github:dprint/dprint"
gersemi = "pipx:gersemi"

[tools]
act = "latest"
just = "latest"
actionlint = "latest"
shellcheck = "latest"
gersemi = "latest"

[tools.dprint]
version = "latest"

[tools.dprint.platforms]
linux-x64 = { asset_pattern = "dprint-x86_64-unknown-linux-gnu.zip" }
linux-arm64 = { asset_pattern = "dprint-aarch64-unknown-linux-gnu.zip" }
