[settings]
lockfile = true

[tool_alias]
gersemi = "pipx:gersemi"
oxfmt = "npm:oxfmt"
precious = "github:houseabsolute/precious"

[tools]
act = "latest"
just = "latest"
actionlint = "latest"
shellcheck = "latest"
gersemi = "latest"
oxfmt = "0.59.0"
precious = "latest"
