[global]
excludes = ["**/*-lock.json", "**/node_modules/**", "out/**", ".venv/**", "**/__pycache__/**"]

[formatter.cpp]
command = "clang-format"
options = ["-i"]
includes = ["*.c", "*.cc", "*.cpp", "*.cxx", "*.h", "*.hh", "*.hpp", "*.hxx", "*.inl"]

[formatter.cmake]
command = "gersemi"
options = ["--in-place", "--no-warn-about-unknown-commands"]
includes = [
  "CMakeLists.txt",
  "**/CMakeLists.txt",
  "CMakeLists.txt.in",
  "**/CMakeLists.txt.in",
  "*.cmake",
  "*.cmake.in",
]

[formatter.python]
command = "uv"
options = ["run", "--locked", "--only-group", "dev", "ruff", "format"]
includes = ["*.py", "*.pyi"]

[formatter.just]
command = "just"
options = ["--fmt", "--unstable", "--justfile"]
includes = ["justfile", "**/justfile", "*.just"]
no-positional-arg-support = true

[formatter.misc]
command = "oxfmt"
options = ["--disable-nested-config"]
includes = ["*.json", "*.jsonc", "*.md", "*.markdown", "*.toml", "*.yaml", "*.yml"]
