name: CI

on:
  push:
  pull_request:

jobs:
  cmake-linux:
    name: Linux C++ (CMake CI Workflow)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy

      - name: Run CMake workflow preset
        run: cmake --workflow --preset ci-linux-all

      - name: Run example
        shell: bash
        run: |
          chmod +x "out/build/ci-linux/mylib_example" || true
          "out/build/ci-linux/mylib_example"

  cmake-windows:
    name: Windows C++ (CMake CI Workflow)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "19"

      - name: Set up environment
        run: |
          $info = vswhere -latest -format json | ConvertFrom-Json
          $module_name = 'Microsoft.VisualStudio.DevShell.dll'
          $module_path = Join-Path $info.installationPath 'Common7' 'Tools' $module_name
          Import-Module $module_path
          Enter-VsDevShell -VsInstanceId $info.instanceId -SkipAutomaticLocation -DevCmdArguments "-arch=x64 -no_logo"
          # Update the current environment:
          Get-ChildItem 'env:' | %{ echo "$($_.Name)=$($_.Value)" >> $env:GITHUB_ENV }

      - name: Run CMake workflow preset
        run: cmake --workflow --preset ci-windows-all

      - name: Run example
        shell: pwsh
        run: |
          ./out/build/ci-windows/Release/mylib_example.exe

  nix:
    name: Nix (flake)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Nix flake show
        run: nix flake show

      - name: Build default package (C++ library)
        run: nix build .#default -L

      - name: Nix flake check
        run: nix flake check -L

      - name: Run C++ example via flake app
        run: nix run .#mylib-example

      - name: Build python-app env
        run: nix build .#python-app -L
